[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["public/**"]
  node_bundler = "nft"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200